sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
#packages required by oracle
      - bc
      - rpm
      - npm
      - node
      - unzip

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_ZIP_DIR=dockerfiles/11.2.0.2
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib:$ORACLE_HOME/bin
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter

before_install:
  - bash .travis/oracle/download.sh

install:
  - docker build --build-arg ORACLE_PWD=oracle --force-rm=true --no-cache=true --shm-size=1G  -t oracle/database:11.2.0.2-xe -f Dockerfile.xe .
  - docker run -p 1521:1521 -p 5500:5500 oracle/database:11.2.0.2-xe

script:
  - bash test.sh


