sudo: required

language: bash

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - NLS_LANG=AMERICAN_AMERICA.AL32UTF8
    - ORACLE_BASE=/u01/app/oracle
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib
    - PATH=$PATH:$ORACLE_HOME/jdbc/lib:$ORACLE_HOME/bin
    - DATABASE_VERSION=11.2.0.2
    - ORACLE_SID=XE
    - DATABASE_NAME=XE
    - ORA_SDTZ='Europe/London' #Needed as a client parameter
    - TZ='Europe/London'       #Needed as a DB Server parameter

install:
  - bash .travis/oracle/download.sh

script:
  - bash test.sh


